version: '3.8'

volumes: 
  dynamodb_data:

services:
  app:
    build: .
    volumes:
      - "./:/app"
    ports:
      - "5000:5000"
    depends_on: 
      - db
  db:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
     - dynamodb_data:/home/dynamodblocal/data
    restart: unless-stopped
    ports:
      - 8000:8000
    user: root
  admin:
    build:
      context: .
      dockerfile: admin.Dockerfile
    ports:
    - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://db:8000
      - AWS_REGION=example
      - AWS_ACCESS_KEY_ID=example
      - AWS_SECRET_ACCESS_KEY=example
    depends_on:
      - db
